
// constants for signing up
const SIGNUP_USER_R_SENT = "SIGNUP_USER_REQUEST_SENT"
const SIGNUP_USER_R_RECEIVED = "SIGNUP_USER_REQUEST_RECEIVED"
const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR"

// constants for signing in
const SIGNIN_USER_R_SENT = "SIGNIN_USER_R_SENT"
const SIGNIN_USER_R_RECEIVED = "SIGNUP_USER_R_RECEIVED"
const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR"

// constants for token 
const USER_TOKEN = "USER_TOKEN"

// constants for user details 
const USER_DETAILS_R_SENT = "USER_DETAILS_R_SENT"
const USER_DETAILS_R_RECIEVED = "USER_DETAILS_R_RECIEVED"
const USER_DETAILS_ERROR = "USER_DETAILS_ERROR"


export {
        SIGNUP_USER_R_SENT,SIGNUP_USER_R_RECEIVED,SIGNUP_USER_ERROR,
        SIGNIN_USER_R_SENT, SIGNIN_USER_R_RECEIVED, SIGNIN_USER_ERROR,
        USER_TOKEN,
        USER_DETAILS_R_SENT,
        USER_DETAILS_R_RECIEVED,
        USER_DETAILS_ERROR,
    }