const SIGNUP_USER_R_SENT = "SIGNUP_USER_REQUEST_SENT"
const SIGNUP_USER_R_RECEIVED = "SIGNUP_USER_REQUEST_RECEIVED"
const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR"


export {SIGNUP_USER_R_SENT,SIGNUP_USER_R_RECEIVED,SIGNUP_USER_ERROR}